#!/bin/bash

# Partial implementation of `blanche`, as a wrapper for `gam`.
#
# [x] -m | --members
# [ ] -v | --verbose
# [x] -i | --info
# [ ] -r | --recursive
# [x] -a | --add-member
# [x] -d | --delete-member
# [ ] -f | --filename # ?
# [x] -C | --create
# [x] -R | --rename # ?
# [x] -dl | --deletelist
# [x] --show-lists
# also: aliases for users
# also: assume lists are @projectalloy.org or configurable

# default
# TODO: add verbose flag
function members () {
    local list=$1

    gam print group-members group $list 2>/dev/null \
        | cut -d, -f 3 \
        | tail -n +2
}

function info() {
    local list=$1

    gam info group $list 2>/dev/null
}

function add_member() {
    local list=$1
    local member=$2

    gam update group $list add member user $member 2>/dev/null
}

function delete_member() {
    local list=$1
    local member=$2

    gam update group $list remove member user $member 2>/dev/null
}

function create_group() {
    local list=$1
    local listname=$2 # TODO: make optional?

    gam create group $list name '"$listname"' \
        allow_external_members true message_moderation_level moderate_none \
        who_can_post_message anyone_can_post is_archived true 2>/dev/null
}

function rename_group() {
    local oldemail=$1
    local newemail=$2

    gam update group $oldemail email $newemail 2>/dev/null
}

function delete_group() {
    local list=$1

    gam delete group $list 2>/dev/null
}

function show_lists() {
    gam print groups 2>/dev/null \
        | tail -n +2
}
